// Build a private snapshot from extraction outputs. Generated content stays out of Git.
//
// 映射规则（对应设计文档 11.2「不能只用数组下标映射」）：
// 旧抽取产物的 legacy id（q6_a3）不保证等于网页回答序号（10006-03）。实测 q6 的
// a3—a10 整体错位一位。因此这里改为「用 quote 回原文反查」建立显式导入清单：
//   1. 逐个 quote 在同一问题的每篇网页回答中做归一化包含匹配；
//   2. 命中最多且明显领先的那篇即为真实来源，记 method=quote_verified；
//   3. 没有 quote 可验证时才回退到序号映射，记 method=index_fallback；
//   4. 同一篇回答被两个抽取文件指向时直接报错，不静默覆盖。
// 清单写入 private-data/map-manifest.json，便于人工复核。
import {readFile, writeFile, readdir, mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {runInNewContext} from 'node:vm';
import {configuration} from '../server/config.mjs';

const config=await configuration();
const privateDataDir=config.privateDataDir;
const reports=resolve(config.collisionDataDir,'实测报告');
const squeeze=value=>String(value ?? '').replace(/\s/g,'');

const context={window:{}};
runInNewContext(await readFile(resolve(privateDataDir,'data.js'),'utf8'),context);
const questions=context.window.ZHIHU_DEMO_DATA.questions;
const answerText=new Map();
for(const question of questions)
  for(const answer of question.answers)
    answerText.set(answer.id,squeeze(answer.paragraphs.filter(p=>!p.includes('〔图片〕')&&!p.includes('〔视频〕')).join('')));

const maps={}, manifest=[], problems=[];
for(let q=1;q<=6;q++){
  const questionId=String(10000+q);
  const dir=q===5?resolve(reports,'20260912_q5_真实首轮/nodes'):resolve(reports,`20260912_全量6问题/q${q}/nodes`);
  let files=[];try{files=await readdir(dir);}catch{continue;}
  const candidates=questions.find(item=>item.id===questionId)?.answers.map(a=>a.id)||[];
  const claims=new Map();
  const parsed=[];
  for(const file of files.filter(f=>/^q\d+_a\d+\.json$/.test(f))){
    const source=JSON.parse(await readFile(resolve(dir,file),'utf8'));
    parsed.push({file,source,index:Number(source.answer_id.match(/_a(\d+)$/)[1])});
  }
  parsed.sort((a,b)=>a.index-b.index);
  for(const {source,index} of parsed){
    const quotes=source.nodes.map(n=>n.quote).filter(Boolean).map(squeeze);
    const scored=candidates.map(id=>({id,hits:quotes.filter(quote=>answerText.get(id)?.includes(quote)).length}))
      .sort((left,right)=>right.hits-left.hits);
    const best=scored[0], runnerUp=scored[1];
    const indexId=`${questionId}-${String(index).padStart(2,'0')}`;
    let answerId=null, method='';
    if(best?.hits && best.hits>(runnerUp?.hits||0)){answerId=best.id;method='quote_verified';}
    else if(candidates.includes(indexId)){answerId=indexId;method=quotes.length?'index_fallback_unverified':'index_fallback_no_quote';}
    if(!answerId){problems.push(`${source.answer_id}：无法确定对应回答，已跳过。`);continue;}
    const entry={answerId,legacyId:source.answer_id,method,quoteHits:best?.hits||0,quoteTotal:quotes.length,
      indexWouldGive:indexId,shifted:answerId!==indexId,source,index};
    const rival=claims.get(answerId);
    if(rival){
      // 同一篇回答被两个抽取文件指向：按「已验证引用数 → 序号也一致 → legacy 序号」确定性取舍，
      // 落选者记录在清单里，不静默覆盖，也不让两份结果随读取顺序互相顶替。
      const win=entry.quoteHits!==rival.quoteHits?entry.quoteHits>rival.quoteHits
        :entry.shifted!==rival.shifted?!entry.shifted
        :entry.index<rival.index;
      const [keep,drop]=win?[entry,rival]:[rival,entry];
      claims.set(answerId,keep);
      problems.push(`${entry.legacyId} 与 ${rival.legacyId} 都指向 ${answerId}（该回答被重复抽取），保留 ${keep.legacyId}，丢弃 ${drop.legacyId}。`);
      continue;
    }
    claims.set(answerId,entry);
  }
  for(const missing of candidates.filter(id=>!claims.has(id)))
    problems.push(`${missing} 没有对应的抽取结果，页面将显示“暂不支持拆解”。`);
  for(const [answerId,entry] of claims){
    const {source,method,quoteHits,quoteTotal,indexWouldGive,shifted,legacyId}=entry;
    manifest.push({answerId,legacyId,method,quoteHits,quoteTotal,indexWouldGive,shifted});
    maps[answerId]={answerId, legacyId, provenance:'saved_extraction', mapping:method,
      groups:source.groups.map(g=>({id:g.group_id,title:g.title,summary:g.summary})),
      nodes:source.nodes.map(n=>({id:n.id,groupId:n.group_id,role:n.role,text:n.claim_text,type:n.type,scope:n.scope,quote:n.quote,grounded:n.grounded,stance:n.question_stance}))};
  }
}

await mkdir(privateDataDir,{recursive:true});
await writeFile(resolve(privateDataDir,'collision-maps.js'),`// Generated by scripts/import-maps.mjs from private extraction outputs.\nwindow.COLLISION_MAPS = ${JSON.stringify(maps)};\n`,'utf8');
manifest.sort((a,b)=>a.answerId.localeCompare(b.answerId));
await writeFile(resolve(privateDataDir,'map-manifest.json'),JSON.stringify({generatedAt:new Date().toISOString(),entries:manifest,problems},null,1)+'\n','utf8');
const shifted=manifest.filter(entry=>entry.shifted);
console.log(`Imported ${Object.keys(maps).length} answer maps.`);
console.log(`按 quote 校验修正了 ${shifted.length} 处序号错位：${shifted.map(entry=>`${entry.legacyId}→${entry.answerId}`).join('、')||'无'}`);
if(problems.length)console.warn('需要人工复核（已写入 private-data/map-manifest.json）：\n- '+problems.join('\n- '));
